version: '2.29.7'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - PETZI_SECRET=super_secret_key
    depends_on:
      - db
  db:
    image: postgres:13  # Utiliser une image PostgreSQL version 13
    environment:
      POSTGRES_USER: user  # Nom d'utilisateur de la base de données
      POSTGRES_PASSWORD: password  # Mot de passe de la base de données
      POSTGRES_DB: petzi_db  # Nom de la base de données
    ports:
      - "5432:5432"  # Exposer le port 5432 de PostgreSQL